### 1.Numpy란?
Numerical Python으로 python에서 **대규모 다차원 배열**을 다룰 수 있게 도와주는 라이브러리.
![](https://velog.velcdn.com/images/knh19950524/post/09f87eeb-cfdb-4375-a0e1-5f84d760f733/image.png)

![](https://velog.velcdn.com/images/knh19950524/post/1fa61619-c587-47ed-a24a-9aa648c9f64b/image.png)
넘파이를 이용한다면 데이터의 대부분을 숫자 배열로 표현 가능하다.
왼쪽의 흑백이미지는 해당 픽셀에 대한 밝기(명암)을 나타내는 2차원 배열 데이터로 표현 가능하고, 오른쪽의 sound data는 시간 대비 음압을 1차원 숫자 배열 데이터로 표현 가능하다.
따라서 넘파이를 이용한다면 실생활의 많은 데이터를 배열로 나타낼 수 있으므로 배열을 효과적으로 바라보고, 가공하는 절차가 중요하다.


물론, 파이썬 리스트를 통해 배열을 나타낼 수 있기는 하지만, 파이썬 리스트에 비해 빠른 연산이 가능하고 효율적으로 메모리를 사용가능하다는 장점이 있다.



In [2]:
#numpy 이용
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
#파이썬 이용
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [8]:
#실수형태의 array (원소 1개라도 실수이면 모두 실수로 나타남)
np.array([3, 1.4, 2, 3, 4])

array([3. , 1.4, 2. , 3. , 4. ])

In [9]:
#2차원 array
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [10]:
#데이터 타입을 지정 가능
np.array([1, 2, 3, 4], dtype='float')

array([1., 2., 3., 4.])

# 배열 데이터 타입 dtype

In [11]:
#python list와는 다르게 array는 단일 타입으로 구성됨.
arr = np.array([1,2,3,4], dtype=float)
arr

array([1., 2., 3., 4.])

In [12]:
arr.dtype

dtype('float64')

In [13]:
arr.astype(int)

array([1, 2, 3, 4])

![](https://velog.velcdn.com/images/knh19950524/post/440718a5-24de-4567-9f64-c8e5a9618952/image.png)

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# 3*5 모양으로 만들어라
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#start, end, step
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 난수로 채워진 배열 만들기

In [18]:
#인자로 튜플을 받는다. 튜플 = shape
np.random.random((2, 2))

array([[0.45108412, 0.92776185],
       [0.03050753, 0.11709345]])

In [19]:
#np.random.normal(평균, 표준편차, shape) : 정규분포
np.random.normal(0, 1, (2, 2))

array([[-1.52816043, -1.5237021 ],
       [-0.81250218,  0.173899  ]])

In [20]:
#np.random.randint(start, end, shape): start부터 end까지 2*2 형태로 출력
np.random.randint(0, 10, (2, 2))

array([[2, 6],
       [0, 4]])

# 배열의 기초

In [22]:
x2 = np.random.randint(10, size=(3,4))
x2.ndim

2

In [23]:
x2.shape

(3, 4)

In [24]:
x2.size

12

In [25]:
x2.dtype

dtype('int64')

# 찾고 잘라내기 : indexing

In [27]:
x=np.arange(7)
x[3]

3

In [28]:
x[7]

IndexError: index 7 is out of bounds for axis 0 with size 7

In [30]:
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6])

# # 찾고 잘라내기 : slicing

In [31]:
x[1:4]

array([1, 2, 3])

In [32]:
x[1:]

array([1, 2, 3, 4, 5, 6])

In [33]:
x[:4]

array([10,  1,  2,  3])

In [34]:
x[::2]

array([10,  2,  4,  6])

# 모양 바꾸기

In [35]:
x = np.arange(8)
x.shape

(8,)

In [37]:
x2 = x.reshape((2,4))
x2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
x2.shape

(2, 4)

# 이어붙이고 나누고 ; concatenate : array를 이어 붙인다.

In [41]:
x = np.array([0,1,2])
y = np.array([3,4,5])
np.concatenate([x,y])

array([0, 1, 2, 3, 4, 5])

In [42]:
matrix = np.arange(4).reshape(2,2)
np.concatenate([matrix, matrix],axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [43]:
matrix = np.arange(4).reshape(2,2)
np.concatenate([matrix, matrix],axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

# np.spli : axis축을 기준으로 나눌 수 있다.

In [44]:
matrix = np.arange(16).reshape(4,4)
upper,lower = np.split(matrix, [3], axis=0)

In [47]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
lower

array([[12, 13, 14, 15]])

In [50]:
matrix = np.arange(16).reshape(4,4)
left,right = np.split(matrix, [3], axis=1)

In [49]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
left

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [52]:
right

array([[ 3],
       [ 7],
       [11],
       [15]])

# 루프는 느리다

In [67]:
#array의 모든 원소에 5를 더해서 만드는 함수
def add_five_to_array(values):
    output = np.empty(len(values)) #받은 길이만큼의 빈 array
    for i in range(len(values)):
        output[i] = values[i] + 5
    return output

In [56]:
values = np.random.randint(1,10, size=5)
values

array([6, 8, 3, 4, 5])

In [68]:
add_five_to_array(values)

array([11., 13.,  8.,  9., 10.])

만약 array의 크기가 크다면?
![](https://velog.velcdn.com/images/knh19950524/post/aab6af54-882e-44d5-8f05-b8f1cbdf3fa2/image.png)

# 기본연산
array는 사칙연산에 대한 기본 연산을 지원한다.

In [70]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [71]:
x+5

array([5, 6, 7, 8])

In [72]:
x-5

array([-5, -4, -3, -2])

In [73]:
x*5

array([ 0,  5, 10, 15])

In [74]:
x/5

array([0. , 0.2, 0.4, 0.6])

다차원 행렬에도 적용가능하다.

In [78]:
x = np.arange(4).reshape((2,2))
y = np.random.randint(10, size=(2,2))
x

array([[0, 1],
       [2, 3]])

In [79]:
y

array([[0, 1],
       [5, 7]])

In [80]:
x+y

array([[ 0,  2],
       [ 7, 10]])

In [81]:
x-y

array([[ 0,  0],
       [-3, -4]])

# 브로드캐스팅

Broadcasting : shape이 다른 array끼리의 연산

In [82]:
np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [83]:
np.arange(3)

array([0, 1, 2])

In [84]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# 집계함수

집계 : 데이터에 대한 요약 통계를 볼 수 있다.

In [85]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
np.sum(x)

28

In [88]:
np.min(x)

0

In [89]:
np.max(x)

7

In [90]:
np.mean(x)

3.5

In [91]:
np.std(x)

2.29128784747792

In [92]:
np.sum(x, axis=0)

array([ 4,  6,  8, 10])

In [93]:
np.sum(x, axis=1)

array([ 6, 22])

# 마스킹 연산

마스킹 연산 : True, Flase array를 통해서 특정 값을 뽑아내는 방법

In [95]:
x = np.arange(5)
x<3

array([ True,  True,  True, False, False])

In [96]:
x>5

array([False, False, False, False, False])

In [97]:
x[x<3] #True인 값들은 추출됨

array([0, 1, 2])